[build]
   command = "npm install && npm run build"
   publish = "/server.js"

[[redirects]]
   from = "/*"
   to = "/api/classify-number"
   status = 200

[[headers]]
   for = "/*"
   [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
